server:
  # 默认端口是8080
  port: 9000
spring:
  application:
    name: msc-gateway
  cloud:
    nacos:
      # 注册中心地址【动态路由需要集成注册中心】
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          # 配置开启与DiscoveryClient整合
          enabled: true
      routes:
        # 路由id
        - id: loadbalancer_route
          # 路由uri地址, loadbalancer://服务名称 【DNS域名解析的思路】
          uri: lb://msc-payment
          predicates:
            # 拦截所有提供者的请求到提供者集群服务
            - Path=/payment/**
