server:
  port: 9001
spring:
  application:
    name: msc-gateway-api
  cloud:
    nacos:
      # 注册中心地址
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      # 该配置能够使dashboard主动发现该应用
      eager: true
      transport:
        # 配置管控台的主机地址+端口
        dashboard: localhost:8888
        # 传输配置数据端口
        port: 8719
    gateway:
      discovery:
        # 配置开启定位器
        locator:
          enabled: true
      routes:
        # 路由到order订单服务
        - id: order_route
          uri: lb://msc-order
          predicates:
            - Path=/order/get/**
        # 路由到payment支付服务
        - id: payment_route
          uri: lb://msc-payment
          predicates:
            - Path=/payment/get/**
