server:
  port: 8888
mybatis:
  # 注册mybatis中实体类的别名
  type-aliases-package: com.hero.bean
  # 注册映射文件
  mapper-locations: classpath:com/hero/dao/*.xml
spring:
  # 注册数据源
  datasource:
    # 指定数据源类型为Druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root
  # 连接Redis服务器
  redis:
    host: 127.0.0.1
    port: 6379

  # 连接Redis高可有集群
  #  redis:
  #    sentinel:
  #      master: mymaster
  #      nodes:
  #        - sentinelOS1:26379
  #        - sentinelOS2:26379
  #        - sentinelOS3:26379

  # 配置缓存
  cache:
    type: redis # 指定缓存类型
    cache-names: realTimeCache   # 指定缓存区域名称
  # 功能等价于spring-boot配置文件中的<dubbo:application/>
  application:
    name: 11-provider-springboot
  # 指定zk注册中心
  dubbo:
    registry: zookeeper://zkOS:2181
  # zk集群作注册中心
  # registry: zookeeper://zkOS1:2181?backup=zkOS2:2181,zkOS3:2181

